# Limit ranges for production namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: production-limit-range
  namespace: multimodal-platform-prod
spec:
  limits:
  # Container limits
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "2"
      memory: "2Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
      
  # Pod limits
  - type: Pod
    max:
      cpu: "4"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
      
  # PVC limits
  - type: PersistentVolumeClaim
    max:
      storage: 20Gi
    min:
      storage: 1Gi