# Pod Disruption Budgets for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: multimodal-platform-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: multimodal-platform-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: websocket-service-pdb
  namespace: multimodal-platform-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: websocket-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service-pdb
  namespace: multimodal-platform-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: user-service-pdb
  namespace: multimodal-platform-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: game-service-pdb
  namespace: multimodal-platform-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: game-service