apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: multimodal-platform
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-service
        app.kubernetes.io/component: user
    spec:
      containers:
      - name: user-service
        image: multimodal-user-service:latest
        ports:
        - containerPort: 8083
          name: http
        env:
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GIN_MODE
        - name: PORT
          value: "8083"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE_URL
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_ADDR
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: multimodal-platform
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: user
spec:
  selector:
    app.kubernetes.io/name: user-service
  ports:
  - port: 8083
    targetPort: 8083
    name: http
  type: ClusterIP