apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: multimodal-platform
  labels:
    app.kubernetes.io/name: websocket-service
    app.kubernetes.io/component: realtime
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: websocket-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: websocket-service
        app.kubernetes.io/component: realtime
    spec:
      containers:
      - name: websocket-service
        image: multimodal-websocket-service:latest
        ports:
        - containerPort: 8081
          name: websocket
        env:
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GIN_MODE
        - name: WS_PORT
          value: "8081"
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_ADDR
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: multimodal-platform
  labels:
    app.kubernetes.io/name: websocket-service
    app.kubernetes.io/component: realtime
spec:
  selector:
    app.kubernetes.io/name: websocket-service
  ports:
  - port: 8081
    targetPort: 8081
    name: websocket
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: websocket-service-hpa
  namespace: multimodal-platform
  labels:
    app.kubernetes.io/name: websocket-service
    app.kubernetes.io/component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: websocket-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80